include(CMakeForceCompiler)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR i386)

set(CMAKE_C_COMPILER   i386-elf-gcc)
set(CMAKE_CXX_COMPILER i386-elf-g++)
set(CMAKE_ASM_COMPILER i386-elf-gcc)
set(CMAKE_LINKER i386-elf-ld)

unset(CMAKE_C_FLAGS CACHE)
set(CMAKE_C_FLAGS "-m32" CACHE STRING "" FORCE)

unset(CMAKE_ASM_FLAGS CACHE)
set(CMAKE_ASM_FLAGS "-m32" CACHE STRING "" FORCE)

unset(CMAKE_C_LINK_FLAGS CACHE)
set(CMAKE_C_LINK_FLAGS "-Xlinker -melf_i386" CACHE STRING "" FORCE)

unset(CMAKE_CXX_FLAGS CACHE)
set(CMAKE_CXX_FLAGS "-m32" CACHE STRING "" FORCE)

unset(CMAKE_CXX_LINK_FLAGS CACHE)
set(CMAKE_CXX_LINK_FLAGS "-Xlinker -melf_i386" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
