#ifndef FLAPJACKOS_KERNEL_INCLUDE_PLATFORM_I386_CONTEXT_SWITCH_HPP
#define FLAPJACKOS_KERNEL_INCLUDE_PLATFORM_I386_CONTEXT_SWITCH_HPP

extern "C" {
void i386_context_switch(char** old_stack_pointer, char* new_stack_pointer);
}

#endif // FLAPJACKOS_KERNEL_INCLUDE_PLATFORM_I386_CONTEXT_SWITCH_HPP
