#ifndef FLAPJACKOS_KERNEL_INCLUDE_PLATFORM_I386_EXTRACT_PAGE_MAP_OPERATION_HPP
#define FLAPJACKOS_KERNEL_INCLUDE_PLATFORM_I386_EXTRACT_PAGE_MAP_OPERATION_HPP

namespace i386 {

class ExtractPageMapOperation {
};

} // namespace i386

#endif // FLAPJACKOS_KERNEL_INCLUDE_PLATFORM_I386_EXTRACT_PAGE_MAP_OPERATION_HPP
