#ifndef FLAPJACKOS_KERNEL_INCLUDE_PLATFORM_I386_KERNEL_ADDRESS_SPACE_BOOTSTRAPPER_HPP
#define FLAPJACKOS_KERNEL_INCLUDE_PLATFORM_I386_KERNEL_ADDRESS_SPACE_BOOTSTRAPPER_HPP

#include "paging_resolver.hpp"
#include <platform/i386/generic_kernel_address_space_bootstrapper.hpp>

namespace i386 {

using KernelAddressSpaceBootstrapper = GenericKernelAddressSpaceBootstrapper<PagingResolver>;

} // namespace i386

#endif // FLAPJACKOS_KERNEL_INCLUDE_PLATFORM_I386_KERNEL_ADDRESS_SPACE_BOOTSTRAPPER_HPP