#ifndef FLAPJACKOS_KERNELPLATFORMSUPPORT_INCLUDE_PLATFORM_I386_PHYSICAL_MEMORY_MAP_HPP
#define FLAPJACKOS_KERNELPLATFORMSUPPORT_INCLUDE_PLATFORM_I386_PHYSICAL_MEMORY_MAP_HPP

#include "generic_physical_memory_map.hpp"
#include "paging_resolver.hpp"

namespace i386 {

using PhysicalMemoryMap = GenericPhysicalMemoryMap<i386::PagingResolver>;

} // namespace i386

#endif // FLAPJACKOS_KERNELPLATFORMSUPPORT_INCLUDE_PLATFORM_I386_PHYSICAL_MEMORY_MAP_HPP