#ifndef FLAPJACKOS_KERNELPLATFORMSUPPORT_INCLUDE_PLATFORM_I386_PROTECTION_FLAGS_HPP
#define FLAPJACKOS_KERNELPLATFORMSUPPORT_INCLUDE_PLATFORM_I386_PROTECTION_FLAGS_HPP

namespace i386 {

constexpr unsigned PAGING_PRESENT = (1 << 0);
constexpr unsigned PAGING_WRITABLE = (1 << 1);

} // namespace i386

#endif // FLAPJACKOS_KERNELPLATFORMSUPPORT_INCLUDE_PLATFORM_I386_PROTECTION_FLAGS_HPP