#!/bin/sh
set -e

BUILD_PREFIX="build"
X86_64_BUILD_DIR="$BUILD_PREFIX/x86_64"
I386_BUILD_DIR="$BUILD_PREFIX/i386"
#TEST32_BUILD_DIR="$BUILD_PREFIX/test_i386"
TEST64_BUILD_DIR="$BUILD_PREFIX/test_x86_64"

CONFIGURE="./scripts/do_configure_build.sh"
"$CONFIGURE" "$X86_64_BUILD_DIR" -DCMAKE_TOOLCHAIN_FILE="x86_64-elf.toolchain.cmake"
"$CONFIGURE" "$I386_BUILD_DIR" -DCMAKE_TOOLCHAIN_FILE="i386-elf.toolchain.cmake"
#"$CONFIGURE" "$TEST32_BUILD_DIR" -DTEST_BUILD_ARCH:string="i386"
"$CONFIGURE" "$TEST64_BUILD_DIR" -DTEST_BUILD_ARCH:string="x86_64"

BUILD="./scripts/do_build.sh"
"$BUILD" "$X86_64_BUILD_DIR"
"$BUILD" "$I386_BUILD_DIR"
#"$BUILD" "$TEST32_BUILD_DIR"
"$BUILD" "$TEST64_BUILD_DIR"
