#!/bin/sh
set -eu

PROJECT_DIR="$(pwd)"
BUILD_PREFIX="$FLAPJACKOS_BUILD_DIR/build"
X86_64_BUILD_DIR="$BUILD_PREFIX/x86_64"
I386_BUILD_DIR="$BUILD_PREFIX/i386"
#TEST32_BUILD_DIR="$BUILD_PREFIX/test_i386"
TEST64_BUILD_DIR="$BUILD_PREFIX/test_x86_64"

CONFIGURE="./scripts/do_configure_build.sh"
"$CONFIGURE" "$PROJECT_DIR" "$X86_64_BUILD_DIR" -DCMAKE_TOOLCHAIN_FILE="x86_64-elf.toolchain.cmake"
"$CONFIGURE" "$PROJECT_DIR" "$I386_BUILD_DIR" -DCMAKE_TOOLCHAIN_FILE="i386-elf.toolchain.cmake"
#"$CONFIGURE" "$PROJECT_DIR" "$TEST32_BUILD_DIR" -DTEST_BUILD_ARCH:string="i386"
"$CONFIGURE" "$PROJECT_DIR" "$TEST64_BUILD_DIR" -DTEST_BUILD_ARCH:string="x86_64"

BUILD="./scripts/do_build.sh"
"$BUILD" "$X86_64_BUILD_DIR"
"$BUILD" "$I386_BUILD_DIR"
#"$BUILD" "$TEST32_BUILD_DIR"
"$BUILD" "$TEST64_BUILD_DIR"
