#ifndef FLAPJACKOS_KERNEL_INCLUDE_LOGICAL_ADDRESSING_HPP
#define FLAPJACKOS_KERNEL_INCLUDE_LOGICAL_ADDRESSING_HPP

#include <cstddef>

// The kernel memory region is fixed at compile time at 32MB.
constexpr size_t KERNEL_MEMORY_REGION_SIZE = 32*1024*1024;

#endif // FLAPJACKOS_KERNEL_INCLUDE_LOGICAL_ADDRESSING_HPP
